import React, { useState } from 'react';
import { FileText, ChevronDown, ChevronUp, Download } from 'lucide-react';
import { MemoSection } from '../types';

interface Props {
  sections:    MemoSection[];
  companyName: string;
  generatedAt: string;
  loading:     boolean;
  onGenerate:  () => void;
}

const Section: React.FC<{ s: MemoSection }> = ({ s }) => {
  const [open, setOpen] = useState(true);
  return (
    <div className="border-b border-surface-border last:border-0">
      <button
        onClick={() => setOpen(o => !o)}
        className="w-full flex items-center justify-between py-3 text-left hover:text-slate-100 transition-colors"
      >
        <span className="text-sm font-semibold text-slate-200">{s.title}</span>
        {open ? <ChevronUp size={14} className="text-slate-500" /> : <ChevronDown size={14} className="text-slate-500" />}
      </button>
      {open && (
        <div className="pb-4 text-sm text-slate-400 leading-relaxed whitespace-pre-wrap fade-in-up">
          {s.content}
        </div>
      )}
    </div>
  );
};

export const MemoPanel: React.FC<Props> = ({ sections, companyName, generatedAt, loading, onGenerate }) => {
  const handleExport = () => {
    const lines = sections.map(s => `## ${s.title}\n\n${s.content}`).join('\n\n---\n\n');
    const full  = `# Investment Memorandum\n## ${companyName}\n*Generated: ${new Date(generatedAt).toLocaleString()}*\n\n---\n\n${lines}\n\n*Generated by AcquiSight AI — not investment advice.*`;
    const blob  = new Blob([full], { type: 'text/markdown' });
    const url   = URL.createObjectURL(blob);
    const a     = document.createElement('a');
    a.href      = url;
    a.download  = `${companyName.replace(/\s+/g, '-')}-Investment-Memo.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="card fade-in-up">
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-2">
          <FileText size={16} className="text-brand-400" />
          <h2 className="text-base font-semibold text-slate-200">AI Investment Memo</h2>
        </div>
        <div className="flex gap-2">
          {sections.length > 0 && (
            <button onClick={handleExport} className="btn-ghost">
              <Download size={14} /> Export
            </button>
          )}
          <button onClick={onGenerate} className="btn-primary" disabled={loading}>
            {loading ? (
              <><span className="inline-block w-3.5 h-3.5 border-2 border-white/30 border-t-white rounded-full animate-spin" /> Generating…</>
            ) : (
              <><FileText size={14} /> {sections.length ? 'Regenerate' : 'Generate Memo'}</>
            )}
          </button>
        </div>
      </div>

      {sections.length === 0 && !loading && (
        <div className="text-center py-10 text-slate-500">
          <FileText size={32} className="mx-auto mb-3 opacity-30" />
          <p className="text-sm">Click "Generate Memo" to produce a PE-style investment memorandum.</p>
          <p className="text-xs mt-1 opacity-60">Requires a screened company result above.</p>
        </div>
      )}

      {loading && (
        <div className="space-y-3 py-2">
          {[...Array(7)].map((_, i) => (
            <div key={i} className="skeleton h-4" style={{ width: `${60 + (i % 3) * 15}%` }} />
          ))}
        </div>
      )}

      {sections.length > 0 && !loading && (
        <div className="mt-1">
          {sections.map((s, i) => <Section key={i} s={s} />)}
        </div>
      )}
    </div>
  );
};
